### ISSUE TITLE
Authentication Problems with Same Proxy Host

### ISSUE THREAD

**Issue by Matir** [foxyproxy/firefox-extension#122]
If you have two proxy configurations using the same host/IP, but with different authentication credentials, then FoxyProxy may not send the correct credentials.

This seems to be because the [authData map is keyed on host](https://github.com/foxyproxy/firefox-extension/blob/master/src/scripts/background.js#L152).

If you're wondering what my use case for this is:

1. Testing a proxy that requires authentication with different accounts with different levels of access
2. Multiple proxies on different ports on the same host with different credentials

**Comment by ericjung** [comment]
Yes, you are correct. Do you think of the key is a combination of host and port the problem would be fixed?

**Comment by paulo-mu-axur** [comment]
Same issue here (v3.0.7.1, Microsoft Edge 96.0.1054.53, Windows 10). Some proxy services allows customers to append country and city codes to the username's value for exit node selection, but still using the same host:port and password. I don't think it would be fixed by combining the host+port as the key..

**Comment by erosman** [comment]
> If you're wondering what my use case for this is:
> 
> - Testing a proxy that requires authentication with different accounts with different levels of access
> - Multiple proxies on different ports on the same host with different credentials



In [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released):
- Authentication
  - Firefox: Tied to the proxy details e.g. Host & Port
  - Chrome: Tied to Host
 - Multiple login for the same proxy is not automatically possible since there is no way to inquire what is the desired login
 However, it might be possible to do so based on patterns e.g. create 2 identical proxy entries but with difference use/pass and set patterns to apply to different targets

**Comment by erosman** [comment]
### [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) update

> Multiple proxies on different ports on the same host with different credentials

- Available in Firefox for HTTP/HTTPS/SOCKS5
- Available in Chrome for HTTP/HTTPS

> Testing a proxy that requires authentication with different accounts with different levels of access

- Not available in FoxyProxy 8.0
- Users can enable/disable a proxy i.e. disable one to login into the other
