### ISSUE TITLE
Proxy per window

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#125]
From support email:

It would be great if you could change the foxyproxy mode for each firefox window - not globally. So the setting will work for any tab within the window. but when you open a new window you can set another mode.

**Comment by erosman** [comment]
Generally speaking, when users open a new window or choose the option to open a link or tab in a new window, or drag tab out to make a new window; the expectation is to continue with the same settings. Otherwise the new tab in new window will be without proxy. Having to set it, besides the inconvenience, it will not work since by the time user gets to the toolbar icon to change something, requests have been sent & page has started to load or loaded.

**Comment by HumanG33k** [comment]
For me a great feature can be to use firefox container to have one proxy setting by container or with the temp container extension by tab. For web dev it can permit to get a look and time loading for a website from different places.

**Comment by erosman** [comment]
**Proxy per window** is not feasible with currently available API.

It is not possible in Chrome as its `proxy.settings` has no access to `window`.
Firefox `proxy.onRequest` does not provide `window` details. While it provides `tabId`, getting the `windowId` through a separate asynchronous API is not practical for every request.

Also: Support for Proxy-Per-Container #132

**Comment by ericjung** [comment]
I think you can ignore windowId and just use tabId.

**Comment by erosman** [comment]
Do you mean proxy per Tab?

Besides the fact that is not possible in Chrome, and considerably costly in Firefox, in practical terms, how would FoxyProxy know which tab to apply it to?

**Comment by ericjung** [comment]
User needs to specify which container to use in the proxy settings window (from a list of containers previously created)

**Comment by erosman** [comment]
It would be better to keep the container discussion in the other thread and keep this topic for per-window discussion.

**Comment by erosman** [comment]
Added Tab Proxy feature (Firefox only) in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension).
