### ISSUE TITLE
Protocols does not match if not protocol is provided

### ISSUE THREAD

**Issue by OlofHaglund** [foxyproxy/firefox-extension#129]
If a protocol is not provided then the pattern won't match.
![Screenshot from 2021-01-03 16-55-39](https://user-images.githubusercontent.com/13319564/103483005-930e4400-4de4-11eb-96e1-8f38db514114.png)
```
  "whitePatterns": [
    {
      "title": "Juice shop",
      "pattern": "localhost:3000",
      "type": 1,
      "protocols": 1,
      "active": true
    }
  ],
  "blackPatterns": []
}
```

I currently running on 84.0.1 (64-bit)
Locally I have installed OWASP Juice Shop and try to redirect the traffic to this site through my proxy.
When entering `http://localhost:3000` in the web browser and the proxy enables and when the site is loaded the URL is changed to only `localhost:3000` and FoxyProxy is no longer enabled.

If no protocol is provided then FoxyProxy should assume a default protocol.

**Comment by ericjung** [comment]
Thank you for writing and including a screenshot!

> When entering http://localhost:3000 in the web browser and the proxy enables and when the site is loaded the URL is changed to only localhost:3000

Firefox changes the URL from http://localhost:3000 to localhost:3000 because you have *browser.urlbar.trimURLs* set to *true* in about:config. Change that value to *false* and you will see the protocol in the URL bar. To be clear, this has nothing to do with FoxyProxy, but I think you understand that. *There is always a protocol for every URL and network request, even if Firefox chooses not to display it to you.*

> and FoxyProxy is no longer enabled.

That is not correct. You can confirm it by:

1. Turn on FoxyProxy (anything but *Turn Off (Use Firefox Settings)*
2. Go  to FoxyProxy Options -> Log. Click the *On* button
3. In new tab, open http://localhost:3000. Value of *browser.urlbar.trimURLs* does not matter.
4. Go back to the FoxyProxy Log and see that http://localhost:3000 is there

> If no protocol is provided then FoxyProxy should assume a default protocol.

When you type a pattern into FoxyProxy, you are forced to provide protocol. It is not possible to enter a pattern without protocol, too:

![image](https://user-images.githubusercontent.com/5875610/103484578-1744d500-4dad-11eb-8bda-42538de6c3e1.png)

Regarding your screenshot that displays no protocol -- that is a testing page for your convenience to assist in writing URL patterns. It is not used for live traffic. Moreover, the page prompts to you include protocol in the default text:

![image](https://user-images.githubusercontent.com/5875610/103484645-aeaa2800-4dad-11eb-9992-c1be676fc72b.png)

and indeed the error message in your screenshot tells you that protocols do not match. It can't be any more clear.

You must remember that *there is always a protocol for every URL and network request, even if Firefox chooses not to display it to you.*
