### ISSUE TITLE
Add search capability to patterns list

### ISSUE THREAD

**Issue by ericjung** [foxyproxy/firefox-extension#130]
From email:

{quote}also add a search patterns because if there is many of them it is hard to search on them thanks{quote}

**Comment by erosman** [comment]
Is the normal search (`Ctrl + F`) insufficient?

**Comment by ericjung** [comment]
I've just tried it on a page with a lot of patterns. It works, but it matches text in the **Name** column, too. It's not useless, but it's not as effective as searching patterns only.

**Comment by erosman** [comment]
That is a little extra benefit for a lot of extra code (bloat).

**Comment by T2JOESl4m2ZpNC** [comment]
Indeed a `Ctrl+F` search does suffice inside of the options page, however a search capability on the popup would be really helpful.

For my use case i got 300+ proxies imported labeled by country code ex: `us99` , it would be great if i just  for example click `/` and start searching through the country codes instead of scrolling

**Comment by erosman** [comment]
Where would be the search area? title, hostname, patterns?

**Comment by T2JOESl4m2ZpNC** [comment]
imo title and hostname,since with patterns foxyproxy will switch hosts according to urls

**Comment by erosman** [comment]
Filter feature is available in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released).

Displayed proxies are filtered based on filter value (case-insensitive).
Title & hostname values are searched.

**Comment by ericjung** [comment]
Great news!!
