### ISSUE TITLE
problem caused by username contains special character when import proxy list

### ISSUE THREAD

**Issue by leoxk** [foxyproxy/firefox-extension#164]
Hi, if the username contains special character, like @ , it will cause problem after import into proxy list.

the username and password is  leo@gmail.com 123456
so the config string should be:  socks5://leo@gmail.com:123456@usa.proxy.com:1080
but after imported, the username have changed. It seems you have encode the special character.

![image](https://user-images.githubusercontent.com/59395/143394716-d38ecbc1-d618-458f-a69d-0e8a186b70f3.png)

**Comment by ericjung** [comment]
This is done by design to prevent XSS attacks in proxy import lists. You can work around it by using the [Simple Format](https://github.com/foxyproxy/firefox-extension/wiki/Import-Proxy-List#simple-format) for importing proxy lists.

if you do not have the proxy list in that format, you can use a find/replace in a text editor that supports regular expressions to quickly convert the proxy list from the "Complete" format to the "Simple" format. Let me know if you need help with that.
