### ISSUE TITLE
Add container support

### ISSUE THREAD

**Issue by agyild** [foxyproxy/firefox-extension#22]
[Container](https://support.mozilla.org/en-US/kb/containers) support would allow using different proxy configurations depending on the container the domain has been visited in. (e.g. For domain example.com: use proxy A when visited in Work profile, use proxy B when visited in Personal, otherwise use proxy C).

**Comment by erosman** [comment]
That sounds good... but ..... the method of using the proxy API in [FoxyPAC](https://addons.mozilla.org/firefox/addon/foxypac/) is to set a PAC. The PAC is handled by Firefox directly.

Containers are Tab features, and use  the webRequest to handle Tab. They are exposed to different data and I am not sure how that can be done.
Additionally, container work for entire domain while you have more freedom with rules in FoxyPAC

However ............. my [FoxyTab](https://addons.mozilla.org/firefox/addon/foxytab/) has a Container support by domain. The data can be copy/paste into FoxyPAC to give you similar result.

It is not a direct approach but it works.
FoxyPAC will proxify those domains.
FoxyTab will set the same to containers.

**Comment by ericjung** [comment]
Hello agyild,

This will be added in a future release to FoxyProxy.

**Comment by eyedeekay** [comment]
Interesting to me that this is coming up, I have been hanging proxy settings onto container tabs in my I2P in Private Browsing extension and would [like to be able to retain compatibility with FoxyProxy, but I don't know how yet](https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox/issues/47). I think we might run into similar issues with other extensions that container-ize tabs automatically based on URL's if FoxyProxy rules start to correspond to container tabs, the best solution might be to keep containers optional so that if a person has a conflicting extension they can turn it off?

**Comment by ericjung** [comment]
@eyedeekay proxy-through-containers will definitely be an option, not forced. Will that meet your needs?

**Comment by eyedeekay** [comment]
For other containerizers(Facebook/Google Container from Mozilla for instance) yes, and for all non-I2P proxies for me, yes, I think so. For I2P Proxies my extension will still probably be incompatible with FoxyProxy because, at least when I tested using them together, my extension settings seem to be used and not FoxyProxy's.

I could do what I do for Snowflake, that is, detect if FoxyProxy is installed and never mess with settings FoxyProxy needs, based on the assumption that the user is only using FoxyProxy to configure their proxy settings and only wants the container features of my plugin. However if I do that I would like to figure out some way to confirm that FoxyProxy has rules for I2P ready. I can't just make a request to proxy.i2p and see if it succeeds, because if no proxy is configured for .i2p domains(By FoxyProxy in this case) then it will leak, so I need a way to determine the presence of the settings without a request to preserve compatibility. If I can't figure out a good way to do that only in my extension, then I may need to request a way to "talk" to FoxyProxy to determine if rules are present to cover a particular pseudo-tld like *.i2p.

**Comment by bug-repport** [comment]
Yes, very need this function! Relase please!

**Comment by ThiefMaster** [comment]
This would indeed be a great feature!  Basically an option to use a proxy regardless of the URL as long as it's in a given container tab.

**Comment by bug-repport** [comment]
> This would indeed be a great feature! Basically an option to use a proxy regardless of the URL as long as it's in a given container tab.

Yes, it would be very cool if you could set up a proxy for a specific tab, and not a domain, this is a great idea, I am ready to sponsor its implementation, 1 thousand dollars your bitcoin adress.

**Comment by vfsoraki** [comment]
This is a great feature to add. I switched to another addon just for this reason, though I will use FoxyProxy when it gets container support.

**Comment by cljoly** [comment]
I totally agree, I *developed* my own extension just for this reason.

**Comment by erosman** [comment]
Follow on: [Incognito & Container Support](https://github.com/foxyproxy/browser-extension/issues/33)
