### ISSUE TITLE
After update, foxyproxy matches any URL against first pattern

### ISSUE THREAD

**Issue by LDVSOFT** [foxyproxy/firefox-extension#37]
Instead of only matching given patterns, FoxyProxy matches ALL URLs on first proxy option, on first pattern. Pattern itself does not contain any wildcards (basically, matches one hostname).

**Comment by ericjung** [comment]
Hi,

Which version are you using? The problem you describe is fixed in 7.3; see https://github.com/foxyproxy/firefox-extension/issues/33

You can force Firefox to update FoxyProxy to 7.3 by:

1. Going to about:add-ons
2. Click the "gear" icon and then "Check for updates"

Please reply with an update do I know if I can close this or there is a new bug.
