### ISSUE TITLE
After update, icon overlay no longer shows proxy info

### ISSUE THREAD

**Issue by mattberther** [foxyproxy/firefox-extension#38]
I recently updated to 7.3, after being on 6+. I've noticed that v7 does not seem to put the name of the proxy currently used over the icon in the toolbar. I was using this to get a visual indicator of what proxy is used.

Is this expected behaviour, and if so, is there a way to turn it back on? If it is not expected, can we get a fix for that, please?

**Comment by ericjung** [comment]
Hi,

Thanks for writing. I'm aware of the problem and an fixing it now. Sorry for the inconvenience.

Eric

**Comment by ericjung** [comment]
You can try a beta of this now. You will not lose any settings. Here are instructions:

1. Download and unzip [7.4 beta](https://github.com/foxyproxy/firefox-extension/archive/7.4.zip)
2. Enter `about:debugging#/runtime/this-firefox` in the Firefox URL bar
3. Click “Load Temporary Add-on”
4. Navigate to where you unzipped in step 1. Select any file in the `src` directory

Again, you will not lose any settings.

**I would greatly appreciate any feedback.** This also fixes issue https://github.com/foxyproxy/firefox-extension/issues/39.

Helping me to test this is how bugs are prevented! Please help.

**Comment by mattberther** [comment]
I see the icon overlays with this beta version! 👍

**Comment by ericjung** [comment]
> I see the icon overlays with this beta version! 👍

Thanks for testing!

**Comment by ericjung** [comment]
This bug/feature is in FoxyProxy 7.4, which is finished and submitted to Mozilla for approval. Recommend Add-ons require manual review and approval by Mozilla before public release, unlike non-recommended add-ons. I expect that to take 1-3 days.

Thanks, @mattberther, for your help testing. This version is solid. I hope you like it.

I will try to post here after it's approved so that you can force Firefox to update instead of waiting for the update to be pushed to you.
