### ISSUE TITLE
Title Label over FoxyProxy Icon limited to 3 characters

### ISSUE THREAD

**Issue by eredisg** [foxyproxy/firefox-extension#51]
In the latest update of Foxy Proxy (v7.4.1), the title label over the extension is 3 characters instead of 4 characters. I usually tend to use the title label to define the port it is set to and due to most of my ports being in the same range 8100, 8110, 8120... etc. It is difficult to see what port the proxy is running on with multiple Firefox sessions open.

**Screenshot**:
![Screenshot](https://imgur.com/kI7IVYh.jpg)

**Details**:
Browser Version: Firefox Developer 72.0b2
Extension Version: FoxyProxy v7.4.1

**Comment by ericjung** [comment]
Hello

Firefox determines how many characters to display there. If it was up to me, I'd display many more than just 3 or 4. 

If you downgrade to the previous version, do you actually see more characters? Because I'm fairly sure nothing has changed for this (and as I said, I really don't have control over how many characters are displayed).

**Comment by ericjung** [comment]
Are you using Firefox Nightly? I think this is a bug in Nightly.

**Comment by eredisg** [comment]
Hello Eric,

Same issue happens with FoxyProxy 7.4 while using Firefox Developer Edition. I tried on standard Firefox and it seems to work fine. So it is most likely a bug with the developer edition.

Thank you for your help!
