### ISSUE TITLE
Browser ignores proxy if launched via url

### ISSUE THREAD

**Issue by moonburnt** [foxyproxy/firefox-extension#60]
**Issue Description:**
If you launch browser by trying to click on link in any other application - the following link **ignores foxyproxy settings completely** (uses default internet connection). At minimum - it leads to **leak of your real IP**. At worst - to inability to open web page, if site has been banned by your ISP.
Luckily, following issue only appears to affect the direct url, you open - if you will try to get to any other link or just reload the same page - it will follow foxyproxy settings correctly.

**Steps to reproduce:**
- Setup foxyproxy to use some socks5 as your current proxy
- Exit all currently running firefox windows
- Re-open browser by following link from some messenger (or just type in terminal: `firefox https://getfoxyproxy.org/geoip/`)

**Expected Behavior:**
Connection to web page happens via proxy (geoip page will show ip of your current proxy)

**Actual Behavior:**
Browser ignores proxy and tries to load page directly (geoip page will show your actual ip)

**Tested on:**
Linux, Firefox 72.0.1, Foxy Proxy Standard 7.4.3

**Comment by ericjung** [comment]
@moonburnt thanks for the report. Unfortunately this behavior is dictated by Firefox and there is nothing web extensions can do about it. One thing I would recommend is to leave Firefox open before launching URLs that way. I did not test this, but I suspect that if Firefox is already open before the URL click, then the problem won't happen. The reason I suspect this is because I'm guessing the root problem here is that web extensions aren't fully loaded by Firefox before the URL loads.

If you leave firefox open then URL click, is the problem still there?

Please note: regardless of the results of the above test, there is nothing I can do to fix the problem since it needs to be fixed in Firefox itself.

**Comment by moonburnt** [comment]
> If you leave firefox open then URL click, is the problem still there?
nope, problem only appears if clicking on link launches browser from zero.

Well, thanks anyway - at this point, I will probably try to report such behavior to mozilla, coz its a bit weird to say the least
