### ISSUE TITLE
Automatically close toolbar menu after choice in Firefox

### ISSUE THREAD

**Issue by mnmelo** [foxyproxy/firefox-extension#75]
Hi and thanks for the great work.

This is a very minor UI feature request:
In Firefox, when I select a proxy from the toolbar icon menu the menu stays open until I click elsewhere.

Is there a use case for leaving it open? I'd rather be able to click my choice and be done with it, as with any regular menu behavior.

Thanks once again

**Comment by ericjung** [comment]
Hi,

Thanks for writing. The use case is: to be able to select one of the buttons (**what's my IP**, **log**, **options**) after switching proxies. Probably the only important one is **what's my IP**; people like to switch proxies then confirm that their IP address or location did actually change.

Is that not something you use? I can consider the behavior you describe since it is indeed the usual behavior of such menus.

Eric

**Comment by mnmelo** [comment]
Ah, that does make sense for that use-case.
I wouldn't know how relevant it is. I have indeed used the "what is my IP" function, but far less than I switch proxies (probably because I use always the same ones and so don't feel the need to check?).

My use-case, as a researcher working from home, is to quickly switch to a work proxy when I need to access intranet material or paywalled scientific literature. I otherwise prefer to have an unproxied connection, hence the frequent switching.

Since the intuitive response of a menu is to auto-close, I'd generally vote for that even if I were checking IP after most proxy changes. But again, you'll probably have a better grasp of the use-cases out there, and of the relevance for them of keeping the menu open.

A cool idea to settle this: a proxy option that makes it auto check IP, in a new tab, upon selection; what do you think?

**Comment by erosman** [comment]
> A cool idea to settle this: a proxy option that makes it auto check IP, in a new tab, upon selection; what do you think?

It is possible to open a "What is my IP" tab every time user changes proxy, but that would be extremely annoying to most users.
It is also possible to check & display IP every time the toolbar popup is opened, but besides the extra resource load, that would be seen as tracking by most users.

**What is my IP** is there to double check if desired, otherwise, the normal expectation is that the user's IP will be the proxy IP.

However ....... the process & UI is completely redesigned in [FoxyProxy v8.0](https://github.com/foxyproxy/browser-extension) (once released) which should help with the issue.
